name: CI (bleeding edge)
# goals: check stability against
# - dev version of numpy, matplotlib and scipy
# - building with future pip default options

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dev upstream
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        python -m pip install --upgrade --pre --extra-index \
           https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
           numpy matplotlib scipy scikit-image

        python -m pip install --pre Cython

    - name: Build amical
      run: |
        python -m pip install --requirement requirements/tests.txt
        python -m pip install --no-build-isolation .

    - name: Run tests
      run: |
        python -m pip freeze
        pytest --color=yes
