name: CI (bleeding edge)
# goals: check stability against
# - dev version of numpy, matplotlib and scipy
# - building with future pip default options

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    name: Test nightly dependencies
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: 3.13-dev

    - uses: astral-sh/setup-uv@1edb52594c857e2b5b13128931090f0640537287 # v5.3.0
      with:
        cache-dependency-glob: |
          **/requirements/tests.txt
          **/pyproject.toml

    - name: Configure uv
      run: |
        echo "UV_PYTHON_PREFERENCE=only-system" >> $GITHUB_ENV
        echo "UV_PYTHON=3.13" >> $GITHUB_ENV
        echo "UV_PRERELEASE=allow" >> $GITHUB_ENV
        echo "UV_INDEX=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" >> $GITHUB_ENV
        echo "UV_INDEX_STRATEGY=unsafe-best-match" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        uv venv
        uv pip install --no-build setuptools wheel numpy matplotlib scipy Cython

    - name: Build
      run: |
        uv pip install --no-build-isolation .
        uv pip install --requirement requirements/tests.txt

    - run: uv pip list

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --color=yes -ra
