name: CI (bleeding edge)
# goals: check stability against
# - dev version of numpy, matplotlib and scipy
# - building with future pip default options

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    name: Test nightly dependencies
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: 3.13-dev

    - uses: astral-sh/setup-uv@d8db0a86d3d88f3017a4e6b8a1e2b234e7a0a1b5 # v4.0.0
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/requirements/tests.txt
          **/pyproject.toml

    - name: Install dependencies
      run: |
        uv venv
        uv pip install setuptools wheel
        uv pip install --pre --no-build numpy matplotlib scipy Cython \
          --extra-index-url \
          https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
          --index-strategy unsafe-best-match

    - name: Build
      run: |
        uv pip install --no-build-isolation .
        uv pip install --requirement requirements/tests.txt

    - run: uv pip list

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --color=yes -ra
