name: CI (bleeding edge)
# goals: check stability against
# - dev version of numpy, matplotlib and scipy

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    name: Test nightly dependencies
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
      with:
        python-version: 3.13
        cache-dependency-glob: |
          **/requirements/tests.txt
          **/pyproject.toml

    - name: Configure uv
      run: |
        echo "UV_PYTHON=3.13" >> $GITHUB_ENV
        echo "UV_PRERELEASE=allow" >> $GITHUB_ENV
        echo "UV_INDEX=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" >> $GITHUB_ENV
        echo "UV_INDEX_STRATEGY=unsafe-best-match" >> $GITHUB_ENV

    - name: Build
      run: |
        uv pip install scipy matplotlib numpy rlic --requirement requirements/tests.txt --no-build
        uv pip install . --no-deps
    - run: uv pip list
    - name: Run tests
      run: |
        pytest --color=yes -ra
