name: CI (bleeding edge)
# goals: check stability against
# - dev version of numpy, matplotlib and scipy
# - building with future pip default options

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # excluding windows for lack of wheels at the tim of writing

    runs-on: ${{ matrix.os }}
    name: Test nightly dependencies
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13-dev

    - uses: yezz123/setup-uv@v4
      with:
        uv-version: 0.2.29
        uv-venv: .venv

    - name: Install dependencies
      # pre-installing kiwisolver (mpl dependency) because it doesn't have
      # wheels at the time of writing so it collides with `--no-build`
      run: |
        uv pip install setuptools wheel
        uv pip install kiwisolver
        uv pip install --pre --no-build numpy matplotlib scipy Cython \
          --extra-index-url \
          https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
          --index-strategy unsafe-best-match

    - name: Build
      run: |
        uv pip install --no-build-isolation .
        uv pip install --requirement requirements/tests.txt

    - run: uv pip list

    - name: Run tests
      run: pytest --color=yes
