name: CD
on:
  push:
    tags: v*
  pull_request:
    paths:
    - .github/workflows/cd.yml
  workflow_dispatch:


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - windows-2019
        - macos-13  # x86_64
        - macos-14  # arm64
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - uses: yezz123/setup-uv@v4
      with:
        uv-version: 0.2.18
        uv-venv: .venv
    - name: Build wheels for CPython
      uses: pypa/cibuildwheel@v2.19.2
      with:
        output-dir: dist

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build sdist
      run: pipx run build --sdist

    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  deploy:
    name: Publish to PyPI
    needs:
    - build_wheels
    - build_sdist

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
    - name: Download sdist
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist

    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: wheels-*
        merge-multiple: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
