name: CD
on:
  push:
    tags: v*
  pull_request:
    paths:
    - .github/workflows/cd.yml
  workflow_dispatch:


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - windows-2019
        - macos-11
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build wheels for CPython
      uses: pypa/cibuildwheel@v2.12.1
      with:
        output-dir: dist
      env:
        CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
        CIBW_SKIP: '*-musllinux_*'
        CIBW_ARCHS_LINUX: x86_64
        CIBW_ARCHS_MACOS: x86_64
        CIBW_ARCHS_WINDOWS: AMD64
        MACOSX_DEPLOYMENT_TARGET: '10.9'
        CIBW_BUILD_VERBOSITY: 1

    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build sdist
      run: pipx run build --sdist

    - name: Upload sdist
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/*.tar.gz

  deploy:
    name: Publish to PyPI
    needs:
    - build_wheels
    - build_sdist

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
    - name: Download sdist
      uses: actions/download-artifact@v3
      with:
        name: sdist
        path: dist

    - name: Download wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.4
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
