name: CI
on:
  pull_request:
  workflow_dispatch:

concurrency:
  # auto-cancel any in-progress job *on the same branch*
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: yezz123/setup-uv@v4
      with:
        uv-version: 0.2.18
        uv-venv: .venv
    - run: |
        uv pip install --upgrade pip
        uv pip install --upgrade check-manifest
        uv pip install --upgrade build
    - name: Check build
      run: |
        python -m check_manifest
        python -m build

  unit-tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        include:
        - os: macos-latest
          python-version: '3.12'
        - os: windows-latest
          python-version: '3.12'
        - os: ubuntu-20.04
          python-version: '3.9'
          deps: minimal

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: yezz123/setup-uv@v4
      with:
        uv-version: 0.2.18
        uv-venv: .venv

    - if: matrix.deps == 'minimal'
      run: |
        uv pip compile pyproject.toml --resolution=lowest-direct | uv pip install -r -

    - name: Build
      run: |
        uv pip install .
        uv pip install --requirement requirements/tests.txt

    - run: uv pip list

    - name: Test
      run: pytest --color=yes

  image-tests:
    name: Image tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: yezz123/setup-uv@v4
      with:
        uv-version: 0.2.18
        uv-venv: .venv
    - name: Build
      run: |
        uv pip install --upgrade pip
        uv pip install .
        uv pip install --requirement requirements/tests.txt

    - run: uv pip list

    - name: Run Image Tests
      run: |
        pytest --color=yes --mpl -m mpl_image_compare \
               --mpl-generate-summary=html \
               --mpl-results-path=lick_pytest_mpl_results \
               --mpl-baseline-path=tests/pytest_mpl_baseline

    - name: Generate new image baseline
      if: failure()
      run: |
        pytest --color=yes --mpl -m mpl_image_compare \
               --mpl-generate-path=lick_pytest_mpl_new_baseline \
               --last-failed

    # always attempt to upload artifacts, even
    # (and especially) in case of failure.
    - name: Upload pytest-mpl report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lick_pytest_mpl_results
        path: lick_pytest_mpl_results/*

    - name: Upload pytest-mpl baseline
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lick_pytest_mpl_new_baseline
        path: lick_pytest_mpl_new_baseline/*
        if-no-files-found: ignore



  typecheck:
    runs-on: ubuntu-latest
    name: type check

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - uses: yezz123/setup-uv@v4
      with:
        uv-version: 0.2.18
        uv-venv: .venv
    - name: Build
      run: |
        uv pip install --upgrade pip
        uv pip install .
        uv pip install --requirement requirements/typecheck.txt

    - run: uv pip list

    - run: mypy src/lick
